var allProducts = [
  {
    "name": "Stylus Allegro Toilet Suite (S Trap)",
    "brand": "Stylus",
    "itemNumber": "4870075",
    "model": "933315W",
    "rrp": 118.5,
    "strap": true,
    "ptrap": false,
    "sSodMin": 150.0,
    "sSodMax": 250.0,
    "pSodMin": 0.0,
    "pSodMax": 0.0,
    "inletType": "Bottom",
    "stfMin": 0.0,
    "stfMax": 380.0,
    "style": "conn",
    "waterRating": 4.0,
    "description": "<p>Combining the best in functional and contemporary design, the Alegro toilet suite is the economical choice for any bathroom style.</p>",
    "features": "<ul><li>Plastic cistern and flush buttons</li><li>Bottom inlet valve</li><li>S trap</li></ul>",
    "heroImage": "Allegro_Image.jpg",
    "lineImage": "Allegro_Tech.jpg",
    "boxImage": "Allegro_Box.jpg"
  },
  {
    "name": "Stylus Allegro Toilet Suite (P Trap)",
    "brand": "Stylus",
    "itemNumber": "4870076",
    "model": "933325W",
    "rrp": 118.5,
    "strap": false,
    "ptrap": true,
    "sSodMin": 0.0,
    "sSodMax": 0.0,
    "pSodMin": 180.0,
    "pSodMax": 190.0,
    "inletType": "Bottom",
    "stfMin": 0.0,
    "stfMax": 380.0,
    "style": "conn",
    "waterRating": 4.0,
    "description": "<p>Combining the best in functional and contemporary design, the Alegro toilet suite is the economical choice for any bathroom style.</p>",
    "features": "<ul><li>Plastic cistern and flush buttons</li><li>Bottom inlet valve</li><li>P trap</li></ul>",
    "heroImage": "Allegro_Image.jpg",
    "lineImage": "Allegro_Tech.jpg",
    "boxImage": "Allegro_Box.jpg"
  },
  {
    "name": "Caroma Uniset II Toilet Suite (S Trap)",
    "brand": "Caroma",
    "itemNumber": "4870256",
    "model": "983685W",
    "rrp": 149.0,
    "strap": true,
    "ptrap": false,
    "sSodMin": 140.0,
    "sSodMax": 240.0,
    "pSodMin": 0.0,
    "pSodMax": 0.0,
    "inletType": "Bottom",
    "stfMin": 0.0,
    "stfMax": 380.0,
    "style": "conn",
    "waterRating": 4.0,
    "description": "<p>The Uniset II features a mid sized modern styled cistern designed for retrofit installations. Suitable for multi purpose applications and can be used where authorised for septic installations.</p>",
    "features": "<ul><li>Bottom inlet cistern</li><li>S trap</li></ul>",
    "heroImage": "UnisetII_Image.jpg",
    "lineImage": "UnisetII_Tech.jpg",
    "boxImage": "UnisetII_Box.jpg"
  },
  {
    "name": "Caroma Uniset II Toilet Suite (P Trap)",
    "brand": "Caroma",
    "itemNumber": "4870257",
    "model": "983695W",
    "rrp": 149.0,
    "strap": false,
    "ptrap": true,
    "sSodMin": 0.0,
    "sSodMax": 0.0,
    "pSodMin": 180.0,
    "pSodMax": 190.0,
    "inletType": "Bottom",
    "stfMin": 0.0,
    "stfMax": 380.0,
    "style": "conn",
    "waterRating": 4.0,
    "description": "<p>The Uniset II features a mid sized modern styled cistern designed for retrofit installations. Suitable for multi purpose applications and can be used where authorised for septic installations.</p>",
    "features": "<ul><li>Bottom inlet cistern</li><li>P trap</li></ul>",
    "heroImage": "UnisetII_Image.jpg",
    "lineImage": "UnisetII_Tech.jpg",
    "boxImage": "UnisetII_Box.jpg"
  },
  {
    "name": "Caroma Midas Toilet Suite (S Trap)",
    "brand": "Caroma",
    "itemNumber": "4870171",
    "model": "933335W",
    "rrp": 199.0,
    "strap": true,
    "ptrap": false,
    "sSodMin": 150.0,
    "sSodMax": 255.0,
    "pSodMin": 0.0,
    "pSodMax": 0.0,
    "inletType": "Bottom",
    "stfMin": 0.0,
    "stfMax": 380.0,
    "style": "conn",
    "waterRating": 4.0,
    "description": "<p>The Caroma Midas suite combines simple, economical styling with superior water saving technology. With its adjustable connector piece, Midas is a practical choice for retrofit applications.</p>",
    "features": "<ul><li>Adjustable connector style</li><li>Bottom inlet</li><li>S trap</li></ul>",
    "heroImage": "Midas_Image.jpg",
    "lineImage": "Midas_Tech.jpg",
    "boxImage": "Midas_Box.jpg"
  },
  {
    "name": "Caroma Midas Toilet Suite (P Trap)",
    "brand": "Caroma",
    "itemNumber": "4870172",
    "model": "933345W",
    "rrp": 199.0,
    "strap": false,
    "ptrap": true,
    "sSodMin": 0.0,
    "sSodMax": 0.0,
    "pSodMin": 180.0,
    "pSodMax": 190.0,
    "inletType": "Bottom",
    "stfMin": 0.0,
    "stfMax": 380.0,
    "style": "conn",
    "waterRating": 4.0,
    "description": "<p>The Caroma Midas suite combines simple, economical styling with superior water saving technology. With its adjustable connector piece, Midas is a practical choice for retrofit applications.</p>",
    "features": "<ul><li>Adjustable connector style</li><li>Bottom inlet</li><li>P trap</li></ul>",
    "heroImage": "Midas_Image.jpg",
    "lineImage": "Midas_Tech.jpg",
    "boxImage": "Midas_Box.jpg"
  },
  {
    "name": "Stylus Prima Toilet Suite (S Trap)",
    "brand": "Stylus",
    "itemNumber": "4870303",
    "model": "PRI201W",
    "rrp": 195.0,
    "strap": true,
    "ptrap": false,
    "sSodMin": 180.0,
    "sSodMax": 260.0,
    "pSodMin": null,
    "pSodMax": null,
    "inletType": "Bottom",
    "stfMin": 0.0,
    "stfMax": 380.0,
    "style": "conn",
    "waterRating": 4.0,
    "description": "<p>The neatly designed Stylus Prima toilet suite has been designed to suite any new or existing bathroom style.</p>",
    "features": "<ul><li>Adjustable connector style</li><li>Bottom inlet</li><li>S trap</li></ul>",
    "heroImage": "Prima_Image_1.jpg",
    "lineImage": "Prima_Tech.jpg",
    "boxImage": "Prima_Box.jpg"
  },
  {
    "name": "Stylus Prima Toilet Suite (P Trap)",
    "brand": "Stylus",
    "itemNumber": "4870304",
    "model": "PRI251W",
    "rrp": 195.0,
    "strap": false,
    "ptrap": true,
    "sSodMin": 0.0,
    "sSodMax": 0.0,
    "pSodMin": 180.0,
    "pSodMax": 190.0,
    "inletType": "Bottom",
    "stfMin": 0.0,
    "stfMax": 380.0,
    "style": "conn",
    "waterRating": 4.0,
    "description": "<p>The neatly designed Stylus Prima toilet suite has been designed to suite any new or existing bathroom style.</p>",
    "features": "<ul><li>Adjustable connector style</li><li>Bottom inlet</li><li>P trap</li></ul>",
    "heroImage": "Prima_Image_1.jpg",
    "lineImage": "Prima_Tech.jpg",
    "boxImage": "Prima_Box.jpg"
  },
  {
    "name": "Caroma Profile 4 Connector Toilet Suite (S Trap)",
    "brand": "Caroma",
    "itemNumber": "4870300",
    "model": "912414W",
    "rrp": 320.0,
    "strap": true,
    "ptrap": false,
    "sSodMin": 165.0,
    "sSodMax": 240.0,
    "pSodMin": 0.0,
    "pSodMax": 0.0,
    "inletType": "Bottom",
    "stfMin": 0.0,
    "stfMax": 380.0,
    "style": "conn",
    "waterRating": 4.0,
    "description": "<p>With its adjustable connector styling, the Profile Connector is the ideal choice for retrofit applications. Cleaning has been made easy with the concealed pan that reduces dusty spots and a hygienic, snap-on detachable seat.</p>",
    "features": "<ul><li>Chrome button assembly</li><li>Vitreous China</li><li>S trap</li></ul>",
    "heroImage": "Profile_Conn_Image.jpg",
    "lineImage": "Profile_Conn_Tech.jpg",
    "boxImage": "Profile_Conn_Box.jpg"
  },
  {
    "name": "Caroma Profile 4 Connector Toilet Suite (P Trap)",
    "brand": "Caroma",
    "itemNumber": "4870301",
    "model": "912424W",
    "rrp": 320.0,
    "strap": false,
    "ptrap": true,
    "sSodMin": 0.0,
    "sSodMax": 0.0,
    "pSodMin": 180.0,
    "pSodMax": 190.0,
    "inletType": "Bottom",
    "stfMin": 0.0,
    "stfMax": 380.0,
    "style": "conn",
    "waterRating": 4.0,
    "description": "<p>With its adjustable connector styling, the Profile Connector is the ideal choice for retrofit applications. It features an easy to clean concealed pan and a hygienic, snap-on detachable seat.</p>",
    "features": "<ul><li>Chrome button assembly</li><li>Vitreous China</li><li>P trap</li></ul>",
    "heroImage": "Profile_Conn_Image.jpg",
    "lineImage": "Profile_Conn_Tech.jpg",
    "boxImage": "Profile_Conn_Box.jpg"
  },
  {
    "name": "Donson Marano Close Coupled Toilet Suite (S Trap)",
    "brand": "Donson",
    "itemNumber": "4870290",
    "model": "MAR210W",
    "rrp": 257.0,
    "strap": true,
    "ptrap": false,
    "sSodMin": 135.0,
    "sSodMax": 145.0,
    "pSodMin": 0.0,
    "pSodMax": 0.0,
    "inletType": "Bottom",
    "stfMin": 0.0,
    "stfMax": 380.0,
    "style": "cc",
    "waterRating": 4.0,
    "description": "<p>The Marano toilet is the modern choice for your bathroom renovation or new bathroom. Featuring modern lines and water saving technology, the Marano is the smart choice.</p>",
    "features": "<ul><li>Bottom inlet cistern</li><li>S trap</li></ul>",
    "heroImage": "Marano_CC_Image.jpg",
    "lineImage": "Marano_CC_Tech.jpg",
    "boxImage": "Marano_CC_Box.jpg"
  },
  {
    "name": "Donson Marano Close Coupled Toilet Suite (P Trap)",
    "brand": "Donson",
    "itemNumber": "4870291",
    "model": "MAR220W",
    "rrp": 257.0,
    "strap": false,
    "ptrap": true,
    "sSodMin": 0.0,
    "sSodMax": 0.0,
    "pSodMin": 180.0,
    "pSodMax": 190.0,
    "inletType": "Bottom",
    "stfMin": 0.0,
    "stfMax": 380.0,
    "style": "cc",
    "waterRating": 4.0,
    "description": "<p>The Marano toilet is the modern choice for your bathroom renovation or new bathroom. Featuring modern lines and water saving technology, the Marano is the smart choice.</p>",
    "features": "<ul><li>Bottom inlet cistern</li><li>P trap</li></ul>",
    "heroImage": "Marano_CC_Image.jpg",
    "lineImage": "Marano_CC_Tech.jpg",
    "boxImage": "Marano_CC_Box.jpg"
  },
  {
    "name": "Caroma Profile 4 Close Coupled Toilet Suite (S Trap)",
    "brand": "Caroma",
    "itemNumber": "4870298",
    "model": "912316W",
    "rrp": 320.0,
    "strap": true,
    "ptrap": false,
    "sSodMin": 135.0,
    "sSodMax": 145.0,
    "pSodMin": 0.0,
    "pSodMax": 0.0,
    "inletType": "Bottom",
    "stfMin": 0.0,
    "stfMax": 380.0,
    "style": "cc",
    "waterRating": 4.0,
    "description": "<p>The Profile toilet suite delivers modern looks and easy clean style for an affordable price. Designed in Australia and made from quality vitreous china, the Caroma Smartflush&reg;  includes Australia's leading water-saving technology.</p>",
    "features": "<ul><li>Close coupled style</li><li>Bottom inlet</li><li>S trap</li></ul>",
    "heroImage": "p912326W_hero.jpg",
    "lineImage": "p912326W_line.jpg",
    "boxImage": "p912326W_box.jpg"
  },
  {
    "name": "Caroma Profile 4 Close Coupled Toilet Suite (P Trap)",
    "brand": "Caroma",
    "itemNumber": "4870299",
    "model": "912326W",
    "rrp": 320.0,
    "strap": false,
    "ptrap": true,
    "sSodMin": 0.0,
    "sSodMax": 0.0,
    "pSodMin": 180.0,
    "pSodMax": 190.0,
    "inletType": "Bottom",
    "stfMin": 0.0,
    "stfMax": 380.0,
    "style": "cc",
    "waterRating": 4.0,
    "description": "<p>The Profile toilet suite delivers modern looks and easy clean style for an affordable price. Designed in Australia and made from quality vitreous china, the Caroma Smartflush&reg;  includes Australia's leading water-saving technology.</p>",
    "features": "<ul><li>Close coupled style</li><li>Bottom inlet</li><li>P trap</li></ul>",
    "heroImage": "p912326W_hero.jpg",
    "lineImage": "p912326W_line.jpg",
    "boxImage": "p912326W_box.jpg"
  },
  {
    "name": "Donson Marano Wall Faced Toilet Suite (Universal Trap)",
    "brand": "Donson",
    "itemNumber": "4870292",
    "model": "MAR100W",
    "rrp": 425.0,
    "strap": true,
    "ptrap": true,
    "sSodMin": 70.0,
    "sSodMax": 160.0,
    "pSodMin": 180.0,
    "pSodMax": 190.0,
    "inletType": "Bottom",
    "stfMin": 0.0,
    "stfMax": 380.0,
    "style": "wf",
    "waterRating": 4.0,
    "description": "<p>The Marano toilet is the modern choice for your bathroom renovation or new bathroom. Featuring wall faced styling and water saving technology, the Marano is the smart choice.</p>",
    "features": "<ul><li>Wall faced styling</li><li>Bottom inlet cistern</li><li>Universal, S or P trap</li></ul>",
    "heroImage": "pMAR100W_hero.jpg",
    "lineImage": "pMAR100W_line.jpg",
    "boxImage": "pMAR100W_box.jpg"
  },
  {
    "name": "Caroma Opal Wall Faced Toilet Suite (Universal Trap)",
    "brand": "Caroma",
    "itemNumber": "4870305",
    "model": "987032W",
    "rrp": 495.0,
    "strap": true,
    "ptrap": true,
    "sSodMin": 80.0,
    "sSodMax": 180.0,
    "pSodMin": 180.0,
    "pSodMax": 190.0,
    "inletType": "Back",
    "stfMin": 385.0,
    "stfMax": 1000.0,
    "style": "wf",
    "waterRating": 4.0,
    "description": "<p>The popular Opal suite is a modern, close coupled design teamed with the latest Caroma Smartflush&reg; water saving technology. The wall faced, fully integrated style reduces dust spots for a low maintenance, easy clean finish.</p>",
    "features": "<ul><li>Wall faced style</li><li>Back inlet</li><li>Universal, S or P trap</li></ul>",
    "heroImage": "p987032W_hero.jpg",
    "lineImage": "p987032W_line.jpg",
    "boxImage": "p987032W_box.jpg"
  },
  {
    "name": "Caroma Profile with Integrated Hand Basin (S Trap)",
    "brand": "Caroma",
    "itemNumber": "4870114",
    "model": "977715W",
    "rrp": "1902-06-02",
    "strap": true,
    "ptrap": false,
    "sSodMin": 135.0,
    "sSodMax": 145.0,
    "pSodMin": 0.0,
    "pSodMax": 0.0,
    "inletType": "Bottom",
    "stfMin": 0.0,
    "stfMax": 380.0,
    "style": "cc",
    "waterRating": 4.0,
    "description": "<p>The Profile 5 toilet suite with Integrated Hand Basin is the first of its kind, with a unique integrated push button and spout combination designed to lower total bathroom water usage. Fresh water is first used for hand washing and then flows into the cistern to ultimately flush the toilet.</p>",
    "features": "<ul><li>Integrated hand basin</li><li>Bottom inlet</li><li>S trap</li></ul>",
    "heroImage": "p977715W_hero.jpg",
    "lineImage": "p977715W_line.jpg",
    "boxImage": "p977715W_box.jpg"
  },
  {
    "name": "Caroma Profile with Integrated Hand Basin (P Trap)",
    "brand": "Caroma",
    "itemNumber": "4870115",
    "model": "977725W",
    "rrp": "1902-06-02",
    "strap": false,
    "ptrap": true,
    "sSodMin": 0.0,
    "sSodMax": 0.0,
    "pSodMin": 180.0,
    "pSodMax": 190.0,
    "inletType": "Bottom",
    "stfMin": 0.0,
    "stfMax": 380.0,
    "style": "cc",
    "waterRating": 4.0,
    "description": "<p>The Profile 5 toilet suite with Integrated Hand Basin is the first of its kind, with a unique integrated push button and spout combination designed to lower total bathroom water usage. Fresh water is first used for hand washing and then flows into the cistern to ultimately flush the toilet.</p>",
    "features": "<ul><li>Integrated hand basin</li><li>Bottom inlet</li><li>P trap</li></ul>",
    "heroImage": "p977715W_hero.jpg",
    "lineImage": "p977715W_line.jpg",
    "boxImage": "p977715W_box.jpg"
  },
  {
    "name": "Caroma Invisi II Metro Toilet",
    "brand": "Caroma",
    "itemNumber": "4820820",
    "model": "716100W",
    "rrp": "1902-07-19T19:55:12+00:00",
    "strap": true,
    "ptrap": true,
    "sSodMin": 80.0,
    "sSodMax": 120.0,
    "pSodMin": 180.0,
    "pSodMax": 190.0,
    "inletType": "Back",
    "stfMin": 385.0,
    "stfMax": 1000.0,
    "style": "btw",
    "waterRating": 4.0,
    "description": "<p>With the perfect balance of performance and appearance the Invisi&trade; Series II wall faced range sit flush to the floor for an integrated streamlined look, smooth sides and sleek lines make care and cleaning easier.</p>",
    "features": "<ul><li>Wall faced style</li><li>Back inlet</li><li>Universal, S or P trap</li></ul>",
    "heroImage": "p716100W_hero.jpg",
    "lineImage": "p716100W_line.jpg",
    "boxImage": "p716100W_box.jpg"
  },
  {
    "name": "Caroma Opal II Easy Height WFCC Toilet Suite",
    "brand": "Caroma",
    "itemNumber": "4870288",
    "model": "985100W",
    "rrp": "1903-07-08",
    "strap": true,
    "ptrap": true,
    "sSodMin": 80.0,
    "sSodMax": 180.0,
    "pSodMin": 180.0,
    "pSodMax": 190.0,
    "inletType": "Back",
    "stfMin": 385.0,
    "stfMax": 1000.0,
    "style": "ceh",
    "waterRating": 4.0,
    "description": "<p>The new generation Opal II range brings polish and streamlined style to Australian bathrooms. With the inclusion of a raised height pan, the Opal II Easy Height allows for easy transfer on and off the seat, ideal for the elderly or people with restricted movement.</p>",
    "features": "<ul><li>Raised height pan for easy on/off transfer</li><li>Back inlet</li><li>Universal, S or P trap</li></ul>",
    "heroImage": "p985100W_hero.jpg",
    "lineImage": "p985100W_line.jpg",
    "boxImage": "p985100W_box.jpg"
  },
  {
    "name": "Caroma Cube Wall Faced Toilet Suite",
    "brand": "Caroma",
    "itemNumber": "0",
    "model": "824615W",
    "rrp": "1904-04-07",
    "strap": true,
    "ptrap": true,
    "sSodMin": 80.0,
    "sSodMax": 185.0,
    "pSodMin": 180.0,
    "pSodMax": 190.0,
    "inletType": "Back",
    "stfMin": 385.0,
    "stfMax": 1000.0,
    "style": "wf",
    "waterRating": 4.0,
    "description": "<p>The Cube toilet gives your bathroom a new dimension. Showcasing the latest in style, it's also cutting edge when it comes to award-winning Smartflush technology, soft close seat and easy to clean contours.</p>",
    "features": "<ul><li>Wall faced style</li><li>Back inlet</li><li>Universal, S or P trap</li></ul>",
    "heroImage": "p824615W_hero.jpg",
    "lineImage": "p824615W_line.jpg",
    "boxImage": "p824615W_box.jpg"
  },
  {
    "name": "Caroma Cube Invisi II Toilet Suite",
    "brand": "Caroma",
    "itemNumber": "0",
    "model": "711100W",
    "rrp": "1903-03-01",
    "strap": true,
    "ptrap": true,
    "sSodMin": 85.0,
    "sSodMax": 120.0,
    "pSodMin": 180.0,
    "pSodMax": 190.0,
    "inletType": "Back",
    "stfMin": 385.0,
    "stfMax": 1000.0,
    "style": "btw",
    "waterRating": 4.0,
    "description": "<p>With the perfect balance of performance and appearance the Invisi Series II wall faced range sits flush to the floor for an integrated streamlined look, smooth sides and sleek lines make care and cleaning easier.</p>",
    "features": "<ul><li>Behind the wall style</li><li>Universal, S or P trap</li></ul>",
    "heroImage": "p711100W_hero.jpg",
    "lineImage": "p711100W_line.jpg",
    "boxImage": "p711100W_box.jpg"
  },
  {
    "name": "Caroma Geo Wall Faced Toilet Suite",
    "brand": "Caroma",
    "itemNumber": "0",
    "model": "984300W",
    "rrp": "1904-05-14",
    "strap": true,
    "ptrap": true,
    "sSodMin": 80.0,
    "sSodMax": 170.0,
    "pSodMin": 180.0,
    "pSodMax": 190.0,
    "inletType": "Back",
    "stfMin": 385.0,
    "stfMax": 1000.0,
    "style": "wf",
    "waterRating": 4.0,
    "description": "<p>Developed after consultation with leading Australian architects and interior designers, Geo is a unique toilet that reflects today's minimalist trend in architecture and design. Geo combines circular, geometric lines with rectangular elements in an easy clean wall faced suite.</p>",
    "features": "<ul><li>Wall faced style</li><li>Back inlet</li><li>Universal, S or P trap</li></ul>",
    "heroImage": "p984300W_hero.jpg",
    "lineImage": "p984300W_line.jpg",
    "boxImage": "p984300W_box.jpg"
  },
  {
    "name": "Caroma Geo Invisi II Toilet Suite",
    "brand": "Caroma",
    "itemNumber": "0",
    "model": "713100W",
    "rrp": "1903-10-19",
    "strap": true,
    "ptrap": true,
    "sSodMin": 85.0,
    "sSodMax": 95.0,
    "pSodMin": 180.0,
    "pSodMax": 190.0,
    "inletType": "Back",
    "stfMin": 385.0,
    "stfMax": 1000.0,
    "style": "btw",
    "waterRating": 4.0,
    "description": "<p>With the perfect balance of performance and appearance the Invisi Series II wall faced range sit flush to the floor for an integrated streamlined look, smooth sides and sleek lines make care and cleaning easier.</p>",
    "features": "<ul><li>WELS 4 star rated, 4.5/3L</li><li>Behind the wall style</li><li>Universal, S or P trap</li></ul>",
    "heroImage": "p713100W_hero.jpg",
    "lineImage": "p713100W_line.jpg",
    "boxImage": "p713100W_box.jpg"
  },
  {
    "name": "Caroma Leda Wall Faced Toilet Suite",
    "brand": "Caroma",
    "itemNumber": "0",
    "model": "989100W",
    "rrp": "1903-05-18",
    "strap": true,
    "ptrap": true,
    "sSodMin": 80.0,
    "sSodMax": 180.0,
    "pSodMin": 180.0,
    "pSodMax": 190.0,
    "inletType": "Back",
    "stfMin": 385.0,
    "stfMax": 1000.0,
    "style": "wf",
    "waterRating": 4.0,
    "description": "<p>The premium close-coupled Leda suite offers the modern designer a timeless, elegantly shaped design with smooth, easy clean lines. Award-winning Caroma Smartflush&reg; technology reduces water usage down to 4.5L per full flush.</p>",
    "features": "<ul><li>Wall faced style</li><li>Back inlet</li><li>Universal, S or P trap</li></ul>",
    "heroImage": "p989100W_hero.jpg",
    "lineImage": "p989100W_line.jpg",
    "boxImage": "p989100W_box.jpg"
  },
  {
    "name": "Caroma Leda Invisi II Toilet Suite",
    "brand": "Caroma",
    "itemNumber": "0",
    "model": "712100W",
    "rrp": "1903-01-13",
    "strap": true,
    "ptrap": true,
    "sSodMin": 85.0,
    "sSodMax": 120.0,
    "pSodMin": 180.0,
    "pSodMax": 190.0,
    "inletType": "Back",
    "stfMin": 385.0,
    "stfMax": 1000.0,
    "style": "btw",
    "waterRating": 4.0,
    "description": "<p>With the perfect balance of performance and appearance the Invisi Series II wall faced range sit flush to the floor for an integrated streamlined look, smooth sides and sleek lines make care and cleaning easier.</p>",
    "features": "<ul><li>Behind the wall style</li><li>Universal, S or P trap</li></ul>",
    "heroImage": "p712100W_hero.jpg",
    "lineImage": "p712100W_line.jpg",
    "boxImage": "p712100W_box.jpg"
  },
  {
    "name": "Caroma Metro Wall Faced Toilet Suite",
    "brand": "Caroma",
    "itemNumber": "0",
    "model": "904639W",
    "rrp": "1902-09-01",
    "strap": true,
    "ptrap": true,
    "sSodMin": 80.0,
    "sSodMax": 180.0,
    "pSodMin": 180.0,
    "pSodMax": 190.0,
    "inletType": "Back",
    "stfMin": 385.0,
    "stfMax": 1000.0,
    "style": "wf",
    "waterRating": 4.0,
    "description": "<p>With a combination of contemporary design and practicality. Metro's stylish flush-fitting installation is ideal for bathroom renovations and makes cleaning a breeze. Low profile chrome plated buttons add to the visual appeal.</p>",
    "features": "<ul><li>Wall faced style</li><li>Back inlet</li><li>Universal, S or P trap</li></ul>",
    "heroImage": "p904639W_hero.jpg",
    "lineImage": "p904639W_line.jpg",
    "boxImage": "p904639W_box.jpg"
  },
  {
    "name": "Caroma Metro Invisi II Toilet Suite",
    "brand": "Caroma",
    "itemNumber": "0",
    "model": "716100W",
    "rrp": "1902-07-20",
    "strap": true,
    "ptrap": true,
    "sSodMin": 85.0,
    "sSodMax": 120.0,
    "pSodMin": 180.0,
    "pSodMax": 190.0,
    "inletType": "Back",
    "stfMin": 385.0,
    "stfMax": 1000.0,
    "style": "btw",
    "waterRating": 4.0,
    "description": "<p>With the perfect balance of performance and appearance the Invisi Series II wall faced range sit flush to the floor for an integrated streamlined look, smooth sides and sleek lines make care and cleaning easier.</p>",
    "features": "<ul><li>Behind the wall style</li><li>Universal, S or P trap</li></ul>",
    "heroImage": "p716100W_hero.jpg",
    "lineImage": "p716100W_line.jpg",
    "boxImage": "p716100W_box.jpg"
  },
  {
    "name": "Caroma Stirling Wall Faced Toilet Suite",
    "brand": "Caroma",
    "itemNumber": "0",
    "model": "987031W",
    "rrp": "1902-06-08",
    "strap": true,
    "ptrap": true,
    "sSodMin": 80.0,
    "sSodMax": 180.0,
    "pSodMin": 180.0,
    "pSodMax": 190.0,
    "inletType": "Back",
    "stfMin": 385.0,
    "stfMax": 1000.0,
    "style": "wf",
    "waterRating": 4.0,
    "description": "<p>The Caroma Stirling suite matches a sharp, modern cistern design with a classic curved pan. The soft close seat provides an innovative detachable feature allowing for easy cleaning.</p>",
    "features": "<ul><li>Wall faced style</li><li>Back inlet</li><li>Universal, S or P trap</li></ul>",
    "heroImage": "p987031W_hero.jpg",
    "lineImage": "p987031W_line.jpg",
    "boxImage": "p987031W_box.jpg"
  },
  {
    "name": "Caroma Cameo Close Coupled Toilet Suite (S trap)",
    "brand": "Caroma",
    "itemNumber": "0",
    "model": "989150W",
    "rrp": "1901-04-04",
    "strap": true,
    "ptrap": false,
    "sSodMin": 90.0,
    "sSodMax": 190.0,
    "pSodMin": 0.0,
    "pSodMax": 0.0,
    "inletType": "Bottom",
    "stfMin": 0.0,
    "stfMax": 380.0,
    "style": "cc",
    "waterRating": 4.0,
    "description": "<p>Unusual measurements can severely limit the range of options available to a renovator or builder. The Caroma Cameo suite has been developed to resolve this problem. The connector can be manipulated to extend a set out between 0-50mm.</p>",
    "features": "<ul><li>Bottom inlet cistern</li><li>S trap</li></ul>",
    "heroImage": "p989150W_hero.jpg",
    "lineImage": "p989150W_line.jpg",
    "boxImage": "p989150W_box.jpg"
  },
  {
    "name": "Caroma Cameo Close Coupled Toilet Suite (P trap)",
    "brand": "Caroma",
    "itemNumber": "0",
    "model": "989155W",
    "rrp": "1901-04-04",
    "strap": false,
    "ptrap": true,
    "sSodMin": 0.0,
    "sSodMax": 0.0,
    "pSodMin": 180.0,
    "pSodMax": 190.0,
    "inletType": "Bottom",
    "stfMin": 0.0,
    "stfMax": 380.0,
    "style": "cc",
    "waterRating": 4.0,
    "description": "<p>Unusual measurements can severely limit the range of options available to a renovator or builder. The Caroma Cameo suite has been developed to resolve this problem. The connector can be manipulated to extend a set out between 0-50mm.</p>",
    "features": "<ul><li>Bottom inlet cistern</li><li>P trap</li></ul>",
    "heroImage": "p989150W_hero.jpg",
    "lineImage": "p989150W_line.jpg",
    "boxImage": "p989150W_box.jpg"
  },
  {
    "name": "Caroma Regal II Close Coupled Toilet Suite (S trap)",
    "brand": "Caroma",
    "itemNumber": "0",
    "model": "951515W",
    "rrp": "1901-06-18",
    "strap": true,
    "ptrap": false,
    "sSodMin": 100.0,
    "sSodMax": 180.0,
    "pSodMin": 0.0,
    "pSodMax": 0.0,
    "inletType": "Bottom",
    "stfMin": 0.0,
    "stfMax": 380.0,
    "style": "cc",
    "waterRating": 4.0,
    "description": "<p>Simple streamlined contours and a modern cistern design are teamed with leading Caroma Smartflush&reg; technology for maximum water-efficiency. This award-winning technology teamed with smart styling is a combination that's great for you and the environment.</p>",
    "features": "<ul><li>Bottom inlet cistern</li><li>S trap</li></ul>",
    "heroImage": "p951515W_hero.jpg",
    "lineImage": "p951515W_line.jpg",
    "boxImage": "p951515W_box.jpg"
  },
  {
    "name": "Caroma Regal II Close Coupled Toilet Suite (P trap)",
    "brand": "Caroma",
    "itemNumber": "0",
    "model": "951525W",
    "rrp": "1901-06-18",
    "strap": false,
    "ptrap": true,
    "sSodMin": 0.0,
    "sSodMax": 0.0,
    "pSodMin": 180.0,
    "pSodMax": 190.0,
    "inletType": "Bottom",
    "stfMin": 0.0,
    "stfMax": 380.0,
    "style": "cc",
    "waterRating": 4.0,
    "description": "<p>With Regal II, simple streamlined contours and a modern cistern design are teamed with leading Caroma Smartflush&reg; technology for maximum water-efficiency. This award-winning technology teamed with smart styling is a combination that's great for you and the environment.</p>",
    "features": "<ul><li>Bottom inlet cistern</li><li>P trap</li></ul>",
    "heroImage": "p951515W_hero.jpg",
    "lineImage": "p951515W_line.jpg",
    "boxImage": "p951515W_box.jpg"
  },
  {
    "name": "Caroma Vintage Toilet Suite (S Trap)",
    "brand": "Caroma",
    "itemNumber": "0",
    "model": "986055W",
    "rrp": "1902-12-07",
    "strap": true,
    "ptrap": false,
    "sSodMin": 165.0,
    "sSodMax": 250.0,
    "pSodMin": 0.0,
    "pSodMax": 0.0,
    "inletType": "Bottom",
    "stfMin": 0.0,
    "stfMax": 380.0,
    "style": "conn",
    "waterRating": 4.0,
    "description": "<p>This exclusive, traditionally styled toilet incorporates authentic design elements from the Australian Federation period. The Vintage seat in Jarrah or Blackwood is complimented by gold or chrome plated fittings, and a stylish dual flush button assembly.</p>",
    "features": "<ul><li>Traditionally styled</li><li>Bottom inlet</li><li>S trap</li></ul>",
    "heroImage": "p986055W_hero.jpg",
    "lineImage": "p986055W_line.jpg",
    "boxImage": "p986055W_box.jpg"
  },
  {
    "name": "Caroma Vintage Toilet Suite (P Trap)",
    "brand": "Caroma",
    "itemNumber": "0",
    "model": " 986065W",
    "rrp": "1902-12-07",
    "strap": false,
    "ptrap": true,
    "sSodMin": 0.0,
    "sSodMax": 0.0,
    "pSodMin": 180.0,
    "pSodMax": 190.0,
    "inletType": "Bottom",
    "stfMin": 0.0,
    "stfMax": 380.0,
    "style": "conn",
    "waterRating": 4.0,
    "description": "<p>This exclusive, traditionally styled toilet incorporates authentic design elements from the Australian Federation period. The Vintage seat in Jarrah or Blackwood is complimented by gold or chrome plated fittings, and a stylish dual flush button assembly.</p>",
    "features": "<ul><li>Traditionally styled</li><li>Bottom inlet</li><li>P trap</li></ul>",
    "heroImage": "p986055W_hero.jpg",
    "lineImage": "p986055W_line.jpg",
    "boxImage": "p986055W_box.jpg"
  },
  {
    "name": "Caroma Retro Sovereign Toilet Suite (S Trap)",
    "brand": "Caroma",
    "itemNumber": "0",
    "model": "901530W",
    "rrp": "1901-06-03",
    "strap": true,
    "ptrap": false,
    "sSodMin": 160.0,
    "sSodMax": 270.0,
    "pSodMin": 0.0,
    "pSodMax": 0.0,
    "inletType": "Bottom",
    "stfMin": 0.0,
    "stfMax": 380.0,
    "style": "conn",
    "waterRating": 4.0,
    "description": "<p>The Sovereign Retro cistern has been specifically designed to cover the footprint of old Caroma and Fowler single flush cisterns, making it the perfect solution for retro-fit applications. Combined with a retro pan, this suite provides a perfect retro-fit solution.</p>",
    "features": "<ul><li>No need to re-tile, footprint covers all old Caroma and Fowler single flush cisterns</li><li>S trap</li></ul>",
    "heroImage": "p901530W_hero.jpg",
    "lineImage": "p901530W_line.jpg",
    "boxImage": "p901530W_box.jpg"
  },
  {
    "name": "Caroma Retro Sovereign Toilet Suite (P Trap)",
    "brand": "Caroma",
    "itemNumber": "0",
    "model": "901540W",
    "rrp": "1901-06-03",
    "strap": false,
    "ptrap": true,
    "sSodMin": 0.0,
    "sSodMax": 0.0,
    "pSodMin": 180.0,
    "pSodMax": 190.0,
    "inletType": "Bottom",
    "stfMin": 0.0,
    "stfMax": 380.0,
    "style": "conn",
    "waterRating": 4.0,
    "description": "<p>The Sovereign Retro cistern has been specifically designed to cover the footprint of old Caroma and Fowler single flush cisterns, making it the perfect solution for retro-fit applications. Combined with a retro pan, this suite provides a perfect retro-fit solution.</p>",
    "features": "<ul><li>No need to re-tile, footprint covers all old Caroma and Fowler single flush cisterns</li><li>P trap</li></ul>",
    "heroImage": "p901540W_hero.jpg",
    "lineImage": "p901540W_line.jpg",
    "boxImage": "p901540W_box.jpg"
  },
  {
    "name": "Fowler Seido Wall Faced Toilet Suite",
    "brand": "Fowler",
    "itemNumber": "0",
    "model": "810455W",
    "rrp": "1903-07-23",
    "strap": true,
    "ptrap": true,
    "sSodMin": 80.0,
    "sSodMax": 180.0,
    "pSodMin": 180.0,
    "pSodMax": 190.0,
    "inletType": "Back",
    "stfMin": 385.0,
    "stfMax": 1000.0,
    "style": "wf",
    "waterRating": 4.0,
    "description": "<p>The Seido Wall Faced toilet suite's close coupled styling combines the soft geometric forms on the pan and cistern to appear as a single unit, eliminating the need for a conventional flush pipe. A secure cistern fixing system is standard which eliminates the need for wall fixing.</p>",
    "features": "<ul><li>Wall faced style</li><li>Back inlet</li><li>Universal, S or P trap</li></ul>",
    "heroImage": "p810455W_hero.jpg",
    "lineImage": "p810455W_line.jpg",
    "boxImage": "p810455W_box.jpg"
  },
  {
    "name": "Fowler  Newport Cube Wall Faced Toilet Suite",
    "brand": "Fowler",
    "itemNumber": "0",
    "model": "985687SC",
    "rrp": "1902-12-20",
    "strap": true,
    "ptrap": true,
    "sSodMin": 80.0,
    "sSodMax": 180.0,
    "pSodMin": 180.0,
    "pSodMax": 190.0,
    "inletType": "Back",
    "stfMin": 385.0,
    "stfMax": 1000.0,
    "style": "wf",
    "waterRating": 4.0,
    "description": "<p>Close-coupled styling and soft geometric forms eliminate the need for a conventional flush pipe. This creates a toilet suite that is both distinctively appealing to the eye while remaining easy to clean. The Fowler quiet, fast-filling inlet valve is fitted as standard.</p>",
    "features": "<ul><li>Wall faced style</li><li>Back inlet</li><li>Universal, S or P trap</li></ul>",
    "heroImage": "p985687SC_hero.jpg",
    "lineImage": "p985687SC_line.jpg",
    "boxImage": "p985687SC_box.jpg"
  },
  {
    "name": "Seido Icon Series II Toilet Suite",
    "brand": "Fowler",
    "itemNumber": "0",
    "model": "715100W",
    "rrp": "1903-04-14",
    "strap": true,
    "ptrap": true,
    "sSodMin": 85.0,
    "sSodMax": 120.0,
    "pSodMin": 180.0,
    "pSodMax": 190.0,
    "inletType": "Back",
    "stfMin": 385.0,
    "stfMax": 1000.0,
    "style": "btw",
    "waterRating": 4.0,
    "description": "<p>The Seido Icon II&trade; toilet suite features a distinctive shape and smooth sides for easy cleaning. With a 620mm projection from the wall, it is suitable for domestic and commercial applications. The concealed cistern and plumbing match space saving with performance.</p>",
    "features": "<ul><li>Behind the wall style</li><li>Back inlet</li><li>Universal, S or P trap</li></ul>",
    "heroImage": "p715100W_hero.jpg",
    "lineImage": "p715100W_line.jpg",
    "boxImage": "p715100W_box.jpg"
  }
]